In [68]:
import pandas as pd

data=pd.read_csv('homework1.csv')

# print(df.to_string())

data

,statistic_yyy,district_code,site_id,village,edu_age_15up_total,edu_doctor_graduated_m,edu_doctor_graduated_f,edu_doctor_ungraduated_m,edu_doctor_ungraduated_f,edu_master_graduated_m,...,edu_juniorvocational_ungraduated_m,edu_juniorvocational_ungraduated_f,edu_primary_graduated_m,edu_primary_graduated_f,edu_primary_ungraduated_m,edu_primary_ungraduated_f,edu_selftaughtl_m,edu_selftaughtl_f,edu_illiterate_m,edu_illiterate_f
0,統計年,區域別代碼,區域別,村里名稱,總計,博畢_男,博畢_女,博肄_男,博肄_女,碩畢_男,...,初肄_男,初肄_女,小畢_男,小畢_女,小肄_男,小肄_女,自修_男,自修_女,不識_男,不識_女
1,109,65000010001,新北市板橋區,留侯里,1455,3,1,2,2,50,...,0,0,26,64,2,4,0,2,0,3
2,109,65000010002,新北市板橋區,流芳里,1290,8,2,2,2,54,...,0,0,22,58,1,3,0,0,0,3
3,109,65000010003,新北市板橋區,赤松里,841,5,3,0,0,40,...,0,0,14,32,0,4,0,0,1,3
4,109,65000010004,新北市板橋區,黃石里,1049,4,3,3,0,32,...,0,0,25,52,0,4,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,109,63000120038,臺北市北投區,關渡里,10152,36,27,15,8,384,...,0,0,414,595,45,60,7,21,24,52
1485,109,63000120039,臺北市北投區,泉源里,2197,9,4,1,1,63,...,0,0,95,148,14,30,5,8,6,19
1486,109,63000120040,臺北市北投區,湖山里,1508,9,4,2,3,36,...,0,0,87,115,15,12,0,5,1,21
1487,109,63000120041,臺北市北投區,大屯里,1145,4,4,1,0,27,...,0,0,68,73,10,11,2,2,3,15
1488,109,63000120042,臺北市北投區,湖田里,861,2,0,0,0,25,...,0,0,58,80,4,6,2,0,2,11

In [69]:
#1
#由於低一行為中文解釋，需要先進行刪除才能在後續整行合併時不會有字串相加導致系統錯誤
data= data.drop(0)
# data

In [70]:
#2
#將特定行的字串轉成整數，才能在後面進行加總
data['edu_age_15up_total']=data["edu_age_15up_total"].astype(int)
#合併相同site_id名稱
data=data.groupby(['site_id'])['edu_age_15up_total'].sum().reset_index()
data

   site_id  edu_age_15up_total
0   新北市三峽區              100240
1   新北市三芝區               20576
2   新北市三重區              342292
3   新北市中和區              368407
4   新北市五股區               78745
5   新北市八里區               35226
6   新北市土城區              209801
7   新北市坪林區                6228
8   新北市平溪區                4214
9   新北市新店區              275067
10  新北市新莊區              364697
11  新北市板橋區              484262
12  新北市林口區               99666
13  新北市樹林區              159080
14  新北市永和區              193665
15  新北市汐止區              185277
16  新北市泰山區               67454
17  新北市淡水區              162474
18  新北市深坑區               21614
19  新北市烏來區                5505
20  新北市瑞芳區               35572
21  新北市石碇區                7036
22  新北市石門區               10534
23  新北市萬里區               19770
24  新北市蘆洲區              176567
25  新北市貢寮區               11127
26  新北市金山區               19255
27  新北市雙溪區                7930
28  新北市鶯歌區               76387
29  臺北市中山區              196999
30  臺北市中正區              130145
31  臺北市信義區              190417
32  臺北市內湖區              242339
33  臺北市北投區              217007
34  臺北市南港區              103816
35  臺北市士林區              244319
36  臺北市大同區              108009
37  臺北市大安區              256673
38  臺北市文山區              232600
39  臺北市松山區              171117
40  臺北市萬華區              164452

In [71]:
#3
#由於目標為新北以及台北，且若要寫程式來將新北以及台北人口excel進行轉入並合併，會稍微花時間，由於僅40列，因此直接一一打入

data.loc[11,"Population"]=557183
data.loc[3,"Population"]=413063
data.loc[10,"Population"]=420927
data.loc[2,"Population"]=386098
data.loc[9,"Population"]=303750
data.loc[37,"Population"]=307129
data.loc[35,"Population"]=282774
data.loc[32,"Population"]=285228
data.loc[38,"Population"]=271339
data.loc[33,"Population"]=253011
data.loc[6,"Population"]=237819
data.loc[29,"Population"]=226852
data.loc[14,"Population"]=220708
data.loc[31,"Population"]=219315
data.loc[15,"Population"]=203864
data.loc[24,"Population"]=202135
data.loc[39,"Population"]=203658
data.loc[40,"Population"]=186428
data.loc[17,"Population"]=179514
data.loc[13,"Population"]=183956
data.loc[30,"Population"]=157567
data.loc[36,"Population"]=125755
data.loc[34,"Population"]=120028
data.loc[0,"Population"]=116642
data.loc[12,"Population"]=116426
data.loc[4,"Population"]=88312
data.loc[28,"Population"]=87073
data.loc[16,"Population"]=78684
data.loc[20,"Population"]=39456
data.loc[5,"Population"]=39573
data.loc[18,"Population"]=23756
data.loc[1,"Population"]=22736
data.loc[23,"Population"]=21801
data.loc[26,"Population"]=21357
data.loc[25,"Population"]=11979
data.loc[22,"Population"]=11755
data.loc[27,"Population"]=8631
data.loc[21,"Population"]=7607
data.loc[7,"Population"]=6719
data.loc[19,"Population"]=6407
data.loc[8,"Population"]=4519

data

   site_id  edu_age_15up_total  Population
0   新北市三峽區              100240    116642.0
1   新北市三芝區               20576     22736.0
2   新北市三重區              342292    386098.0
3   新北市中和區              368407    413063.0
4   新北市五股區               78745     88312.0
5   新北市八里區               35226     39573.0
6   新北市土城區              209801    237819.0
7   新北市坪林區                6228      6719.0
8   新北市平溪區                4214      4519.0
9   新北市新店區              275067    303750.0
10  新北市新莊區              364697    420927.0
11  新北市板橋區              484262    557183.0
12  新北市林口區               99666    116426.0
13  新北市樹林區              159080    183956.0
14  新北市永和區              193665    220708.0
15  新北市汐止區              185277    203864.0
16  新北市泰山區               67454     78684.0
17  新北市淡水區              162474    179514.0
18  新北市深坑區               21614     23756.0
19  新北市烏來區                5505      6407.0
20  新北市瑞芳區               35572     39456.0
21  新北市石碇區                7036      7607.0
22  新北市石門區               10534     11755.0
23  新北市萬里區               19770     21801.0
24  新北市蘆洲區              176567    202135.0
25  新北市貢寮區               11127     11979.0
26  新北市金山區               19255     21357.0
27  新北市雙溪區                7930      8631.0
28  新北市鶯歌區               76387     87073.0
29  臺北市中山區              196999    226852.0
30  臺北市中正區              130145    157567.0
31  臺北市信義區              190417    219315.0
32  臺北市內湖區              242339    285228.0
33  臺北市北投區              217007    253011.0
34  臺北市南港區              103816    120028.0
35  臺北市士林區              244319    282774.0
36  臺北市大同區              108009    125755.0
37  臺北市大安區              256673    307129.0
38  臺北市文山區              232600    271339.0
39  臺北市松山區              171117    203658.0
40  臺北市萬華區              164452    186428.0

In [72]:
#4
#將受教育人口數進行合併，並排名
data['台北/新北受教育人口數排名'] = data.edu_age_15up_total.rank(method='first',ascending=False)
#依據該地區在台北/新北受教育人口進行排名
data.sort_values("台北/新北受教育人口數排名",inplace=True)
data

   site_id  edu_age_15up_total  Population  台北/新北受教育人口數排名
11  新北市板橋區              484262    557183.0            1.0
3   新北市中和區              368407    413063.0            2.0
10  新北市新莊區              364697    420927.0            3.0
2   新北市三重區              342292    386098.0            4.0
9   新北市新店區              275067    303750.0            5.0
37  臺北市大安區              256673    307129.0            6.0
35  臺北市士林區              244319    282774.0            7.0
32  臺北市內湖區              242339    285228.0            8.0
38  臺北市文山區              232600    271339.0            9.0
33  臺北市北投區              217007    253011.0           10.0
6   新北市土城區              209801    237819.0           11.0
29  臺北市中山區              196999    226852.0           12.0
14  新北市永和區              193665    220708.0           13.0
31  臺北市信義區              190417    219315.0           14.0
15  新北市汐止區              185277    203864.0           15.0
24  新北市蘆洲區              176567    202135.0           16.0
39  臺北市松山區              171117    203658.0           17.0
40  臺北市萬華區              164452    186428.0           18.0
17  新北市淡水區              162474    179514.0           19.0
13  新北市樹林區              159080    183956.0           20.0
30  臺北市中正區              130145    157567.0           21.0
36  臺北市大同區              108009    125755.0           22.0
34  臺北市南港區              103816    120028.0           23.0
0   新北市三峽區              100240    116642.0           24.0
12  新北市林口區               99666    116426.0           25.0
4   新北市五股區               78745     88312.0           26.0
28  新北市鶯歌區               76387     87073.0           27.0
16  新北市泰山區               67454     78684.0           28.0
20  新北市瑞芳區               35572     39456.0           29.0
5   新北市八里區               35226     39573.0           30.0
18  新北市深坑區               21614     23756.0           31.0
1   新北市三芝區               20576     22736.0           32.0
23  新北市萬里區               19770     21801.0           33.0
26  新北市金山區               19255     21357.0           34.0
25  新北市貢寮區               11127     11979.0           35.0
22  新北市石門區               10534     11755.0           36.0
27  新北市雙溪區                7930      8631.0           37.0
21  新北市石碇區                7036      7607.0           38.0
7   新北市坪林區                6228      6719.0           39.0
19  新北市烏來區                5505      6407.0           40.0
8   新北市平溪區                4214      4519.0           41.0

In [73]:
#5
#用受教育人口數/該地區人口總數，並以rate名稱進行存取
data['rate']=data['edu_age_15up_total']/data['Population']
#將其轉入成百分比
data["rate_percentage"] = data["rate"].apply(lambda x: format(x,".2%"))
data

,site_id,edu_age_15up_total,Population,台北/新北受教育人口數排名,rate,rate_percentage
11,新北市板橋區,484262,557183.0,1.0,0.869126,86.91%
3,新北市中和區,368407,413063.0,2.0,0.891891,89.19%
10,新北市新莊區,364697,420927.0,3.0,0.866414,86.64%
2,新北市三重區,342292,386098.0,4.0,0.886542,88.65%
9,新北市新店區,275067,303750.0,5.0,0.905570,90.56%
37,臺北市大安區,256673,307129.0,6.0,0.835717,83.57%
35,臺北市士林區,244319,282774.0,7.0,0.864008,86.40%
32,臺北市內湖區,242339,285228.0,8.0,0.849633,84.96%
38,臺北市文山區,232600,271339.0,9.0,0.857230,85.72%
33,臺北市北投區,217007,253011.0,10.0,0.857698,85.77%
6,新北市土城區,209801,237819.0,11.0,0.882188,88.22%
29,臺北市中山區,196999,226852.0,12.0,0.868403,86.84%
14,新北市永和區,193665,220708.0,13.0,0.877472,87.75%
31,臺北市信義區,190417,219315.0,14.0,0.868235,86.82%
15,新北市汐止區,185277,203864.0,15.0,0.908826,90.88%
24,新北市蘆洲區,176567,202135.0,16.0,0.873510,87.35%
39,臺北市松山區,171117,203658.0,17.0,0.840217,84.02%
40,臺北市萬華區,164452,186428.0,18.0,0.882121,88.21%
17,新北市淡水區,162474,179514.0,19.0,0.905077,90.51%
13,新北市樹林區,159080,183956.0,20.0,0.864772,86.48%
30,臺北市中正區,130145,157567.0,21.0,0.825966,82.60%
36,臺北市大同區,108009,125755.0,22.0,0.858884,85.89%
34,臺北市南港區,103816,120028.0,23.0,0.864932,86.49%
0,新北市三峽區,100240,116642.0,24.0,0.859382,85.94%
12,新北市林口區,99666,116426.0,25.0,0.856046,85.60%
4,新北市五股區,78745,88312.0,26.0,0.891668,89.17%
28,新北市鶯歌區,76387,87073.0,27.0,0.877275,87.73%
16,新北市泰山區,67454,78684.0,28.0,0.857277,85.73%
20,新北市瑞芳區,35572,39456.0,29.0,0.901561,90.16%
5,新北市八里區,35226,39573.0,30.0,0.890152,89.02%
18,新北市深坑區,21614,23756.0,31.0,0.909833,90.98%
1,新北市三芝區,20576,22736.0,32.0,0.904996,90.50%
23,新北市萬里區,19770,21801.0,33.0,0.906839,90.68%
26,新北市金山區,19255,21357.0,34.0,0.901578,90.16%
25,新北市貢寮區,11127,11979.0,35.0,0.928876,92.89%
22,新北市石門區,10534,11755.0,36.0,0.896129,89.61%
27,新北市雙溪區,7930,8631.0,37.0,0.918781,91.88%
21,新北市石碇區,7036,7607.0,38.0,0.924938,92.49%
7,新北市坪林區,6228,6719.0,39.0,0.926924,92.69%
19,新北市烏來區,5505,6407.0,40.0,0.859216,85.92%
8,新北市平溪區,4214,4519.0,41.0,0.932507,93.25%

In [74]:
#6
data['台北/新北受教育百分比排名'] = data.rate.rank(method='first',ascending=False)
data.sort_values("台北/新北受教育百分比排名",inplace=True)
data

,site_id,edu_age_15up_total,Population,台北/新北受教育人口數排名,rate,rate_percentage,台北/新北受教育百分比排名
8,新北市平溪區,4214,4519.0,41.0,0.932507,93.25%,1.0
25,新北市貢寮區,11127,11979.0,35.0,0.928876,92.89%,2.0
7,新北市坪林區,6228,6719.0,39.0,0.926924,92.69%,3.0
21,新北市石碇區,7036,7607.0,38.0,0.924938,92.49%,4.0
27,新北市雙溪區,7930,8631.0,37.0,0.918781,91.88%,5.0
18,新北市深坑區,21614,23756.0,31.0,0.909833,90.98%,6.0
15,新北市汐止區,185277,203864.0,15.0,0.908826,90.88%,7.0
23,新北市萬里區,19770,21801.0,33.0,0.906839,90.68%,8.0
9,新北市新店區,275067,303750.0,5.0,0.905570,90.56%,9.0
17,新北市淡水區,162474,179514.0,19.0,0.905077,90.51%,10.0
1,新北市三芝區,20576,22736.0,32.0,0.904996,90.50%,11.0
26,新北市金山區,19255,21357.0,34.0,0.901578,90.16%,12.0
20,新北市瑞芳區,35572,39456.0,29.0,0.901561,90.16%,13.0
22,新北市石門區,10534,11755.0,36.0,0.896129,89.61%,14.0
3,新北市中和區,368407,413063.0,2.0,0.891891,89.19%,15.0
4,新北市五股區,78745,88312.0,26.0,0.891668,89.17%,16.0
5,新北市八里區,35226,39573.0,30.0,0.890152,89.02%,17.0
2,新北市三重區,342292,386098.0,4.0,0.886542,88.65%,18.0
6,新北市土城區,209801,237819.0,11.0,0.882188,88.22%,19.0
40,臺北市萬華區,164452,186428.0,18.0,0.882121,88.21%,20.0
14,新北市永和區,193665,220708.0,13.0,0.877472,87.75%,21.0
28,新北市鶯歌區,76387,87073.0,27.0,0.877275,87.73%,22.0
24,新北市蘆洲區,176567,202135.0,16.0,0.873510,87.35%,23.0
11,新北市板橋區,484262,557183.0,1.0,0.869126,86.91%,24.0
29,臺北市中山區,196999,226852.0,12.0,0.868403,86.84%,25.0
31,臺北市信義區,190417,219315.0,14.0,0.868235,86.82%,26.0
10,新北市新莊區,364697,420927.0,3.0,0.866414,86.64%,27.0
34,臺北市南港區,103816,120028.0,23.0,0.864932,86.49%,28.0
13,新北市樹林區,159080,183956.0,20.0,0.864772,86.48%,29.0
35,臺北市士林區,244319,282774.0,7.0,0.864008,86.40%,30.0
0,新北市三峽區,100240,116642.0,24.0,0.859382,85.94%,31.0
19,新北市烏來區,5505,6407.0,40.0,0.859216,85.92%,32.0
36,臺北市大同區,108009,125755.0,22.0,0.858884,85.89%,33.0
33,臺北市北投區,217007,253011.0,10.0,0.857698,85.77%,34.0
16,新北市泰山區,67454,78684.0,28.0,0.857277,85.73%,35.0
38,臺北市文山區,232600,271339.0,9.0,0.857230,85.72%,36.0
12,新北市林口區,99666,116426.0,25.0,0.856046,85.60%,37.0
32,臺北市內湖區,242339,285228.0,8.0,0.849633,84.96%,38.0
39,臺北市松山區,171117,203658.0,17.0,0.840217,84.02%,39.0
37,臺北市大安區,256673,307129.0,6.0,0.835717,83.57%,40.0
30,臺北市中正區,130145,157567.0,21.0,0.825966,82.60%,41.0

In [75]:
import pandas as pd

datata=pd.read_csv('homework1.csv')

# print(df.to_string())

datata=datata.drop(0)
# datata=datata.astype(int)

datata=datata.iloc[:,[2,4,7,8,11,12,15,16,19,20,23,24,27,28,31,32,33,34,37,38,41,42,45,46,49,50]]
# datata=datata.astype(int)
datata

,site_id,edu_age_15up_total,edu_doctor_ungraduated_m,edu_doctor_ungraduated_f,edu_master_ungraduated_m,edu_master_ungraduated_f,edu_university_ungraduated_m,edu_university_ungraduated_f,edu_juniorcollege_2ys_ungraduated_m,edu_juniorcollege_2ys_ungraduated_f,...,edu_juniorcollege_5ys_first3y_ungraduated_m,edu_juniorcollege_5ys_first3y_ungraduated_f,edu_junior_ungraduated_m,edu_junior_ungraduated_f,edu_juniorvocational_ungraduated_m,edu_juniorvocational_ungraduated_f,edu_primary_ungraduated_m,edu_primary_ungraduated_f,edu_illiterate_m,edu_illiterate_f
1,新北市板橋區,1455,2,2,10,4,55,44,7,2,...,4,5,5,5,0,0,2,4,0,3
2,新北市板橋區,1290,2,2,10,12,42,30,3,5,...,6,6,7,11,0,0,1,3,0,3
3,新北市板橋區,841,0,0,11,10,32,22,4,4,...,2,4,4,8,0,0,0,4,1,3
4,新北市板橋區,1049,3,0,6,7,44,19,3,4,...,3,2,3,6,0,0,0,4,1,2
5,新北市板橋區,1698,4,1,22,14,54,39,12,6,...,0,0,9,7,0,0,6,4,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,臺北市北投區,10152,15,8,75,64,308,252,56,45,...,44,42,73,71,0,0,45,60,24,52
1485,臺北市北投區,2197,1,1,16,3,60,65,12,6,...,7,9,26,14,0,0,14,30,6,19
1486,臺北市北投區,1508,2,3,7,6,43,29,8,5,...,4,4,22,3,0,0,15,12,1,21
1487,臺北市北投區,1145,1,0,1,9,30,27,7,2,...,14,6,10,2,0,0,10,11,3,15
1488,臺北市北投區,861,0,0,3,0,19,28,5,1,...,4,2,10,5,0,0,4,6,2,11

In [76]:
#6
#由於在後面需要利用迴圈，因此需要所有欄位名稱，並需要刪除site_id，由於不能直接就刪除該行，因此需要存入到list中
list=[]
for i in datata:
    list.append(i)
list.remove('site_id')

In [77]:
#7
#利用迴圈將特定行轉成整數，用0123應該也可以
datata['ungraduated_sum']=0
for i in list:
    datata[i]=datata[i].astype(int)
    
list.remove('edu_age_15up_total')
for j in list:
    print(j)
    print(datata[j])
    datata['ungraduated_sum']+=datata[j]
上面這樣的迴圈有問題!
    
    
datata['graduated_sum']=datata['edu_age_15up_total']-datata['ungraduated_sum']
datata

SyntaxError: invalid syntax (156941524.py, line 12)

In [78]:
#8
#將全部行進行合併，但不合並到site_id以及edu_age_15up_total
datata=datata.groupby(['site_id'])['ungraduated_sum','graduated_sum','edu_age_15up_total', 'edu_doctor_ungraduated_m', 'edu_doctor_ungraduated_f', 'edu_master_ungraduated_m', 'edu_master_ungraduated_f', 'edu_university_ungraduated_m', 'edu_university_ungraduated_f', 'edu_juniorcollege_2ys_ungraduated_m', 'edu_juniorcollege_2ys_ungraduated_f', 'edu_juniorcollege_5ys_final2y_ungraduated_m', 'edu_juniorcollege_5ys_final2y_ungraduated_f', 'edu_senior_ungraduated_m', 'edu_senior_ungraduated_f', 'edu_seniorvocational_ungraduated_m', 'edu_seniorvocational_ungraduated_f', 'edu_juniorcollege_5ys_first3y_ungraduated_m', 'edu_juniorcollege_5ys_first3y_ungraduated_f', 'edu_junior_ungraduated_m', 'edu_junior_ungraduated_f', 'edu_juniorvocational_ungraduated_m', 'edu_juniorvocational_ungraduated_f', 'edu_primary_ungraduated_m', 'edu_primary_ungraduated_f', 'edu_illiterate_m', 'edu_illiterate_f'].sum().reset_index()
datata

C:\Users\shawn\AppData\Local\Temp\ipykernel_4116\732833152.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  datata=datata.groupby(['site_id'])['ungraduated_sum','graduated_sum','edu_age_15up_total', 'edu_doctor_ungraduated_m', 'edu_doctor_ungraduated_f', 'edu_master_ungraduated_m', 'edu_master_ungraduated_f', 'edu_university_ungraduated_m', 'edu_university_ungraduated_f', 'edu_juniorcollege_2ys_ungraduated_m', 'edu_juniorcollege_2ys_ungraduated_f', 'edu_juniorcollege_5ys_final2y_ungraduated_m', 'edu_juniorcollege_5ys_final2y_ungraduated_f', 'edu_senior_ungraduated_m', 'edu_senior_ungraduated_f', 'edu_seniorvocational_ungraduated_m', 'edu_seniorvocational_ungraduated_f', 'edu_juniorcollege_5ys_first3y_ungraduated_m', 'edu_juniorcollege_5ys_first3y_ungraduated_f', 'edu_junior_ungraduated_m', 'edu_junior_ungraduated_f', 'edu_juniorvocational_ungraduated_m', 'edu_juniorvocational_ungraduated_f', 'edu_primary_ungraduated_m', 'edu_primary_ungraduated_f', 'edu_illiterate_m', 'edu_illiterate_f'].sum().reset_index()

KeyError: "Columns not found: 'ungraduated_sum', 'graduated_sum'"

In [79]:
#9
#將該地區肄業人數的比率進行排名
datata['rate']=datata['ungraduated_sum']/datata['edu_age_15up_total']
datata['graduated_rate']=datata['graduated_sum']/datata['edu_age_15up_total']
datata["rate_percentage"] = datata["rate"].apply(lambda x: format(x,".2%"))
datata["graduated_rate_percentage"] = datata["graduated_rate"].apply(lambda x: format(x,".2%"))
datata

KeyError: 'ungraduated_sum'

In [80]:
#10
#排名後，由小到大進行排列
datata['ungraduated_sum_rank'] = datata.rate.rank(method='first',ascending=True)

datata=datata.groupby(['site_id'])['ungraduated_sum','rate',"rate_percentage","ungraduated_sum_rank",'edu_age_15up_total', 'edu_doctor_ungraduated_m', 'edu_doctor_ungraduated_f', 'edu_master_ungraduated_m', 'edu_master_ungraduated_f', 'edu_university_ungraduated_m', 'edu_university_ungraduated_f', 'edu_juniorcollege_2ys_ungraduated_m', 'edu_juniorcollege_2ys_ungraduated_f', 'edu_juniorcollege_5ys_final2y_ungraduated_m', 'edu_juniorcollege_5ys_final2y_ungraduated_f', 'edu_senior_ungraduated_m', 'edu_senior_ungraduated_f', 'edu_seniorvocational_ungraduated_m', 'edu_seniorvocational_ungraduated_f', 'edu_juniorcollege_5ys_first3y_ungraduated_m', 'edu_juniorcollege_5ys_first3y_ungraduated_f', 'edu_junior_graduated_m', 'edu_junior_ungraduated_m', 'edu_junior_ungraduated_f', 'edu_juniorvocational_graduated_m', 'edu_juniorvocational_ungraduated_m', 'edu_juniorvocational_ungraduated_f', 'edu_primary_ungraduated_m', 'edu_primary_ungraduated_f', 'edu_selftaughtl_m', 'edu_illiterate_m', 'edu_illiterate_f'].sum().reset_index()

datata.sort_values("ungraduated_sum_rank",inplace=True)

datata

AttributeError: 'DataFrame' object has no attribute 'rate'

In [81]:
#11
#將data中台北/新北受教育人口數排名和台北/新北受教育百分比排名抓出來
df1=data[['site_id','台北/新北受教育人口數排名','台北/新北受教育百分比排名']]

In [82]:
#12
#更改datata欄位名稱
datata = datata.rename(columns={'ungraduated_sum_rank': '台北/新北肄業比例排名'})
datata

,site_id,edu_age_15up_total,edu_doctor_ungraduated_m,edu_doctor_ungraduated_f,edu_master_ungraduated_m,edu_master_ungraduated_f,edu_university_ungraduated_m,edu_university_ungraduated_f,edu_juniorcollege_2ys_ungraduated_m,edu_juniorcollege_2ys_ungraduated_f,...,edu_juniorcollege_5ys_first3y_ungraduated_m,edu_juniorcollege_5ys_first3y_ungraduated_f,edu_junior_ungraduated_m,edu_junior_ungraduated_f,edu_juniorvocational_ungraduated_m,edu_juniorvocational_ungraduated_f,edu_primary_ungraduated_m,edu_primary_ungraduated_f,edu_illiterate_m,edu_illiterate_f
1,新北市板橋區,1455,2,2,10,4,55,44,7,2,...,4,5,5,5,0,0,2,4,0,3
2,新北市板橋區,1290,2,2,10,12,42,30,3,5,...,6,6,7,11,0,0,1,3,0,3
3,新北市板橋區,841,0,0,11,10,32,22,4,4,...,2,4,4,8,0,0,0,4,1,3
4,新北市板橋區,1049,3,0,6,7,44,19,3,4,...,3,2,3,6,0,0,0,4,1,2
5,新北市板橋區,1698,4,1,22,14,54,39,12,6,...,0,0,9,7,0,0,6,4,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,臺北市北投區,10152,15,8,75,64,308,252,56,45,...,44,42,73,71,0,0,45,60,24,52
1485,臺北市北投區,2197,1,1,16,3,60,65,12,6,...,7,9,26,14,0,0,14,30,6,19
1486,臺北市北投區,1508,2,3,7,6,43,29,8,5,...,4,4,22,3,0,0,15,12,1,21
1487,臺北市北投區,1145,1,0,1,9,30,27,7,2,...,14,6,10,2,0,0,10,11,3,15
1488,臺北市北投區,861,0,0,3,0,19,28,5,1,...,4,2,10,5,0,0,4,6,2,11

In [83]:
#13
#將data中台北/新北肄業比例排名抓出來
df2=datata[['site_id','台北/新北肄業比例排名']]

KeyError: "['台北/新北肄業比例排名'] not in index"

In [84]:
#14
#將df1和df2進行合併，how="left"，以df1為基準，而df1與df2以site_id做交集，進行合併，
df = pd.merge(df1, df2, how='left', on='site_id') 
df

   site_id  台北/新北受教育人口數排名  台北/新北受教育百分比排名  台北/新北肄業比例排名
0   新北市平溪區           41.0            1.0         41.0
1   新北市貢寮區           35.0            2.0         39.0
2   新北市坪林區           39.0            3.0         31.0
3   新北市石碇區           38.0            4.0         36.0
4   新北市雙溪區           37.0            5.0         40.0
5   新北市深坑區           31.0            6.0         23.0
6   新北市汐止區           15.0            7.0         16.0
7   新北市萬里區           33.0            8.0         35.0
8   新北市新店區            5.0            9.0         10.0
9   新北市淡水區           19.0           10.0         19.0
10  新北市三芝區           32.0           11.0         32.0
11  新北市金山區           34.0           12.0         38.0
12  新北市瑞芳區           29.0           13.0         37.0
13  新北市石門區           36.0           14.0         33.0
14  新北市中和區            2.0           15.0         14.0
15  新北市五股區           26.0           16.0         27.0
16  新北市八里區           30.0           17.0         30.0
17  新北市三重區            4.0           18.0         24.0
18  新北市土城區           11.0           19.0         22.0
19  臺北市萬華區           18.0           20.0         15.0
20  新北市永和區           13.0           21.0          7.0
21  新北市鶯歌區           27.0           22.0         29.0
22  新北市蘆洲區           16.0           23.0         26.0
23  新北市板橋區            1.0           24.0         18.0
24  臺北市中山區           12.0           25.0          3.0
25  臺北市信義區           14.0           26.0          5.0
26  新北市新莊區            3.0           27.0         20.0
27  臺北市南港區           23.0           28.0         12.0
28  新北市樹林區           20.0           29.0         25.0
29  臺北市士林區            7.0           30.0          9.0
30  新北市三峽區           24.0           31.0         28.0
31  新北市烏來區           40.0           32.0         34.0
32  臺北市大同區           22.0           33.0         13.0
33  臺北市北投區           10.0           34.0         11.0
34  新北市泰山區           28.0           35.0         21.0
35  臺北市文山區            9.0           36.0          8.0
36  新北市林口區           25.0           37.0         17.0
37  臺北市內湖區            8.0           38.0          6.0
38  臺北市松山區           17.0           39.0          2.0
39  臺北市大安區            6.0           40.0          1.0
40  臺北市中正區           21.0           41.0          4.0

延伸
將新北/台北市地圖匯入，看是否能夠合併變成一個立體圖表，例如有三種顏色圖，分別為受教育人口數、受教育比率以及肄業比率，並以顏色深至淺來表示各地區的情況。

問題
在一開始時， 一一輸入的資料為整個年齡層的人口數，但homework1.csv的檔案是以15歲以上進行統計，雖然各地區在15歲以下在整個年齡層的比例都差不多，但還是影響到台北/新北受教育人口數排名和台北/新北受教育百分比排名這兩個欄位，修正方案：找是否有個地區15歲以上的人口數，而不是全部年齡層人口數。